# version: "3.8"

services:
  exploration:
    # container_name: exploration
    build:
      context: .                                        # folder to use as build context
      dockerfile: .devcontainer/Dockerfile.dx            # Data Exploration
      target: dev
    image: exploration                                  # name of the built image
    volumes:
      - ./:/app:cached
    # working_dir: /app/src
    working_dir: /app
    ports:
      - "8888:8888"
    tty: true
    stdin_open: true
    command: sh
