[project]
name = "ml-med-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbc-driver-manager>=1.5.0",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "pyodbc>=5.2.0",
    "sqlalchemy>=2.0.40",
]
